// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxldevypyjmlezyosstf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bGRldnlweWptbGV6eW9zc3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjQ1MjYsImV4cCI6MjA2MzU0MDUyNn0.pUvEmygByMEhaR2aVTMt5qCWIS03W_RVzr3pWnB8HF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);